### ISSUE TITLE
Unable to update parameter [windDirectionVertical] with value [0] because not in range ['2', '4', '5', '6', '7', '8']. Use default instead.

### ISSUE THREAD

**Issue by DeimicUser** [gvigroux/hon#100]
Logger: custom_components.hon.device
Source: custom_components/hon/device.py:143
Integration: hOn ([documentation](https://github.com/gvigroux/hon), [issues](https://github.com/gvigroux/hon/issues))
First occurred: 16:01:06 (1 occurrences)
Last logged: 16:01:06

Unable to update parameter [windDirectionVertical] with value [0] because not in range ['2', '4', '5', '6', '7', '8']. Use default instead.

**Comment by gvigroux** [comment]
When did you receive this warning ? After which action ?
It seems the integrations tries to update the [windDirectionVertical] with 0 but, 0 is not part of the list I use in the code

**Comment by gvigroux** [comment]
Your problem is different, you use the value 6, which is in theory allowed :)
I will look into it

**Comment by gvigroux** [comment]
@lechoooo do you have the same error whatever the value you set ? (Far left...)

**Comment by gvigroux** [comment]
I found the issue ! I will fix it soon :)

**Comment by lechoooo** [comment]
Great ! Let me know if I can post some more info.

**Comment by gvigroux** [comment]
@lechoooo  I just published the 0.6.0 with the fix :) 
@DeimicUser, please open a new issue and explain how you can push the 0 value to this parameter

**Comment by lechoooo** [comment]
Thanks!
