### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by KevinVeenman** [gvigroux/hon#102]
After adding the repository through HACS and restarting, adding the account (HON, with supported devices, location Europe) the account initializes and then fails to set up. Multiple restarts later and re-adding the repo no different result.  Directly in the HON app, all works as expected. 

Any thoughts?

![image](https://github.com/gvigroux/hon/assets/6702963/69cf2b95-5259-4b18-ae56-3b8dc1af943c)
Home Assistant 2023.7.3

Log: 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/__init__.py", line 71, in async_setup_entry
    coordinator = await hon.async_get_coordinator(appliance)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/hon.py", line 90, in async_get_coordinator
    coordinator = HonBaseCoordinator( self._hass, self, appliance)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/base.py", line 34, in __init__
    self._type_id       = appliance["applianceTypeId"]
                          ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'applianceTypeId'

**Comment by hajtuJ** [comment]
Same issue happen for me. I did provide correct password and username but still this error occur.

**Comment by gvigroux** [comment]
Ok I know how to fix it, I guess there is an incorrect entry somewhere.

@hajtuJ do you have the same error?

**Comment by KevinVeenman** [comment]
> Ok I know how to fix it, I guess there is an incorrect entry somewhere.
> 
> @hajtuJ do you have the same error?

Thanks for looking into this. Lemme know if I can support you with a donation of a  "cup of coffee" :)

**Comment by gvigroux** [comment]
Hi @KevinVeenman, I just made an update. Can you please test and tell me the result ? at minimum you should have a different log with more info.

**Comment by KevinVeenman** [comment]
Hey @gvigroux, thanks for the update. Unfortunately no success just yet.  I get the following log message (see below). 

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hon/device.py:20
Integration: hOn (documentation, issues)
First occurred: 10:51:13 PM (1 occurrences)
Last logged: 10:51:13 PM

Error setting up entr [LOGIN EMAIL] for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/__init__.py", line 72, in async_setup_entry
    coordinator.device = HonDevice(hon, coordinator, appliance)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/device.py", line 20, in __init__
    self._type_id       = appliance["applianceTypeId"]
                          ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'applianceTypeId'

**Comment by gvigroux** [comment]
Thank for your support :)
I've decided to have a more strict approach, so you should not have any issue anymore (but maybe some devices will not appears).

If one device is missing after loading the integration:

1. please add these lines in you configuration.yaml and reboot

```
logger:
  logs:
    custom_components.hon: debug
```
2. after the reboot, look at the log and share the first log called "All appliances:"



Other question, do you have devices using Farenheit?

**Comment by gvigroux** [comment]
@KevinVeenman , @hajtuJ can you please do a new test?

**Comment by gvigroux** [comment]
I'm closing this due to lack of feedback
