### ISSUE TITLE
Dryer dry levels reversed

### ISSUE THREAD

**Issue by craigsbits** [gvigroux/hon#109]
I believe the dry levels are reversed h-1 is iron dry & h-3 is extra dry.

**Comment by craigsbits** [comment]
![Screenshot_20230920-232849](https://github.com/gvigroux/hon/assets/55210737/5d657aac-d48c-4890-a3dd-7c10163ab4c6)

**Comment by gvigroux** [comment]
It's just a naming issue ? or the H-X is also incorrect ?

**Comment by craigsbits** [comment]
Naming issue

**Comment by gvigroux** [comment]
I just made the update (sorry about the delay)

**Comment by craigsbits** [comment]
Thanks.  Just downloaded your integration.
