### ISSUE TITLE
is it possible to use Stop/pause/keep fresh options?

### ISSUE THREAD

**Issue by Jaykurb** [gvigroux/hon#110]
I've checked the programme options, but I cannot find anything for the Stop/pause cycle, is this possible? 

Also, my hon app has an option for 'keep fresh', which starts after the completed cycle to keep the clothes fresh. How would I add this to the parameters? (if possible)

**Comment by gvigroux** [comment]
Did you checked this: https://github.com/gvigroux/hon#how-to-run-any-program ?
All the options will be accessible through services

**Comment by Jaykurb** [comment]
Yes, I tried that, but unfortunately, it wasn't listed.

**Comment by gvigroux** [comment]
It is possible through the mobile hOn app ?

**Comment by Jaykurb** [comment]
![image](https://github.com/gvigroux/hon/assets/49797976/7c20a0f1-95cd-4fb3-9362-cde3dbc477cc) keep fresh is an option when selecting the programme on hon app.


![image](https://github.com/gvigroux/hon/assets/49797976/1f05882c-f181-4f26-9506-3d97bb14c2c1)
During the cycle you have the option to pause or stop

**Comment by gvigroux** [comment]
In order to help, I will need to get all the info of: https://github.com/gvigroux/hon#how-to-run-any-program ?
it should be an option hidden into a program or a speciifc program
