### ISSUE TITLE
DATA_RATE_MEGABITS_PER_SECOND TEMP_CELSIUS TIME_MINUTES

### ISSUE THREAD

**Issue by DeimicUser** [gvigroux/hon#117]
Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 10:52:23 (4 occurrences)
Last logged: 10:52:23

DATA_RATE_MEGABITS_PER_SECOND was used from hon, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.MEGABITS_PER_SECOND instead, please create a bug report at https://github.com/gvigroux/hon/issues
TEMP_CELSIUS was used from hon, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/gvigroux/hon/issues
TIME_MINUTES was used from hon, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please create a bug report at https://github.com/gvigroux/hon/issues

**Comment by gvigroux** [comment]
Done in 0.6.9
