### ISSUE TITLE
HA 2024.1 warnings

### ISSUE THREAD

**Issue by Theo16** [gvigroux/hon#118]
Since HA 2024.1 i have those warnings in logs:

`TEMP_CELSIUS was used from hon, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/gvigroux/hon/issues
TIME_MINUTES was used from hon, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please create a bug report at https://github.com/gvigroux/hon/issues
DATA_RATE_MEGABITS_PER_SECOND was used from hon, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfDataRate.MEGABITS_PER_SECOND instead, please create a bug report at https://github.com/gvigroux/hon/issues`

**Comment by gvigroux** [comment]
done in 0.6.9
