### ISSUE TITLE
Reduce scan interval

### ISSUE THREAD

**Issue by balloob** [gvigroux/hon#120]
Hi from Home Assistant 👋 

I had a call with Haier Europe this morning. They see heavy load on their servers and want to work with the Home Assistant community to create an integration in Home Assistant Core based on a push-based API.

While that work is ongoing, I want to ask if this integration could reduce it's scan interval to 60 seconds instead of 30 seconds. 

https://github.com/gvigroux/hon/blob/c2da8a6cfc106d60daff942c0366bcadaa5faca8/custom_components/hon/base.py#L26C1-L26C51

This will reduce the load on the Haier servers.

Thanks,
Paulus

**Comment by gvigroux** [comment]
Sure, I will upload a new version soon

**Comment by gvigroux** [comment]
Done
