### ISSUE TITLE
Temperature sensors missing

### ISSUE THREAD

**Issue by nikudj** [gvigroux/hon#126]
Hello

Can I somehow add the temperature sensors?

And another ting I don't understand how to use the code from the notifications

My device is
candy
CCE7T620EX
Fridge
Firmware: 5.15.0

**Comment by gvigroux** [comment]
I'm not sure to understand your request. Do you see some temperature value in the device screen ?

**Comment by nikudj** [comment]
![image](https://github.com/gvigroux/hon/assets/6630671/413291ab-8530-41c9-b058-40b5131c7e24)
This is what i can see
Only the set values not the actual ones

**Comment by nikudj** [comment]
On the device screen I can see only the set values 
And in the HA 
![Screenshot_20240304-223606](https://github.com/gvigroux/hon/assets/6630671/12cbff5f-b80c-45c6-b1f6-82a2ae419946)

The question was if i can add the sensors to see the real values
Real value I can see only from the room temperature 

And if I press the get program details or get settings details I get some notifications with some code and I don't understand how can I use it

**Comment by gvigroux** [comment]
For fridge, it seems only the "targeted temperatures" are available. I can only display what is available.
Just look in the official hOn app, you should not be able to see real values as well.

**Comment by nikudj** [comment]
Thanks for the answer

In the hOn app I can't see the actual temperature as well
Is there another way to connect to the fridge?
Tried the Candy simply-Fi but it doesn't seem to work for my device

As for the second part of the question
I have to put that code in an automation?

I am new to the HA and steel learning

**Comment by gvigroux** [comment]
Sorry, it seems that hOn is not able to access these values. So nothing we can do :(
