### ISSUE TITLE
Homeassistant components climate

### ISSUE THREAD

**Issue by Kazionauta** [gvigroux/hon#128]
I have AS25S2SF1FA-S in 2x1 configuration with one outdoor unit. I noticed this bug in logs. 

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Klimat (documentation, issues)
First occurred: 7 marca 2024 16:24:49 (2 occurrences)
Last logged: 7 marca 2024 16:24:49
Entity None (<class 'custom_components.hon.climate.HonClimateEntity'>) implements HVACMode(s): heat, cool, auto, off, fan_only, dry and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/gvigroux/hon/issues

**Comment by gvigroux** [comment]
Yes, I saw this as well on my side. It's due to a recent change in HA Core. I'm looking to fix it.

**Comment by gvigroux** [comment]
Done in 0.6.13
