### ISSUE TITLE
Problem with other HoN integrations

### ISSUE THREAD

**Issue by johnzvis** [gvigroux/hon#129]
If you want to have two different HoN integration installed. Lets say for testing purpose, you have a problem since this integration have the same "name" as other. 

**Example:**
This: https://github.com/gvigroux/hon/
Other: https://github.com/Andre0512/hon/

I installed one first (not remember which one) and then the second to check the difference. Now, everything is mixed mode. In UI they are both showing under HoN, but in other places they are not the same. Then, if you remove one, it still shows as it is installed (no matter which one you remove first. 

It would be nice if they are in different name space.

**Comment by gvigroux** [comment]
I already tried to change the namespace to avoid the collision with the Andre's integration but I need to change a lot of things.
I close this one because there are already one ticket open: https://github.com/gvigroux/hon/issues/105
