### ISSUE TITLE
States have changed to numerical since latest updates

### ISSUE THREAD

**Issue by Jaykurb** [gvigroux/hon#131]
I updated the HA OS and this integration recently, and now the status of my washing machine is showing as a numerical value only. As you can see in the attached screenshot, the UI shows the washing machine state as `running`, but the dev tools indicate that the state is `2`. I can make edits to accommodate numerical values, but I wanted to confirm if this change is permanent or if it will revert back to how it was before.

![Screenshot 2024-03-18 at 11 55 07](https://github.com/gvigroux/hon/assets/49797976/3c976074-f21d-49e3-8333-8a807292671a)

**Comment by gvigroux** [comment]
It's not normal because it should user the list below for the Washing Machine. I've made an update, can you please test the last version?

"0": "Disconnected",
"1": "Ready",
"2": "Running",
"3": "Paused",
"5": "Scheduled",
"6": "Error",
"7": "Finished"

**Comment by Jaykurb** [comment]
I updated it to 0.6.16 but I am still getting numerical values.

![Screenshot 2024-03-19 at 14 00 03](https://github.com/gvigroux/hon/assets/49797976/f9b13328-3b15-4e08-83db-5f40bff30a01)

**Comment by stickmanbrad** [comment]
I can confirm I’m also having this exact issue. I also updated to 0.6.16, and it’s still doing this numeric state. Hopefully this can be easily resolved. Kind regards :-)

**Comment by gvigroux** [comment]
not normal at all... let me check this

**Comment by gvigroux** [comment]
Could you please check in the logs and tell me the "applianceTypeId" value ?
To activate logs, you can add the lines below in your configuration.yaml

```
logger:
  logs:
    custom_components.hon: debug
```

**Comment by willhaggan** [comment]
Just to add, I have found quite the opposite with my Hoover HDISH 700 Dishwasher, after 0.6.12 i was losing entities all together so i stuck .12. After updating to 0.6.15 i have now got the correct information for program name, phase and mode which was always mixed up prior to .15.

**Comment by Jaykurb** [comment]
> applianceTypeId

'applianceTypeId': 1

**Comment by stickmanbrad** [comment]
Has there been any progress on this? - I did see an update was pushed but I’m still seeing numbers? Can provide more information following @Jaykurb ‘s response if needed. Kind regards :-)

**Comment by gvigroux** [comment]
I'm really stick on this one:
- now the "mode" and "programs" naming are in the local file to respect the new HA policy.
- So I've a mapping in EN for all values in the translations folder
- It works for climate, dishwasher and oven but not for washing machines !

I guess there is an error on my side but I'm still looking into it

**Comment by gvigroux** [comment]
I'm not able to find the error on the washing machines... can someone share an account for one day or two (in private) ? I will obviously not touch anything just try to understand why the mapping fails.

**Comment by Jaykurb** [comment]
> mapping

I don't mind doing this but I won't be able to do it till Wednesday as I am away.

**Comment by gvigroux** [comment]
Perfect, let's do it later this week :)

**Comment by Jaykurb** [comment]
> Perfect, let's do it later this week :)

Hi, sorry was a bit of manic week. I am ready whenever you are.

**Comment by gvigroux** [comment]
You can send me some credentials here: gvigroux@free.fr

**Comment by gvigroux** [comment]
I've made an update :) please try

**Comment by Jaykurb** [comment]
![Screenshot 2024-04-18 at 14 39 31](https://github.com/gvigroux/hon/assets/49797976/bad0d15a-93a2-4362-ad00-95698015af5b)

Not working for me, unfortunately.

**Comment by gvigroux** [comment]
If you want to launch a program, you should do something different. What are you trying to achieve ? (I can also test on my side thanks to you)

**Comment by Jaykurb** [comment]
Sorry, I think I misunderstood. 

I thought the update was addressing the issue where the washing machine state changed to numerical value only. 

I mean it isn't a big deal being numerical anyway.

**Comment by gvigroux** [comment]
There are multiple values. With your machine I have only one numerical value, all the rest is text:
Program phase      "ready"
Program name       "Perfect White"
Mode                     "ready"

I've added the program code (136) in case it's usefull

![Capture2](https://github.com/gvigroux/hon/assets/1864287/cdce04f7-1b9a-4d00-bad9-1e7e961c5571)

**Comment by Jaykurb** [comment]
Yes I have text within HA UI but the states seem to be numerical still when viewed in developer tools. 

![image](https://github.com/gvigroux/hon/assets/49797976/6ecf243f-d975-492c-a0b5-5f667d6d9a74)

![image](https://github.com/gvigroux/hon/assets/49797976/e26bada0-67be-41b7-a4c5-eb4551cd1d5f)

I have changed my automations to cater for numerical states now so it doesn't bother me too much. 

Will take a look at the update later when home though, thank you.

**Comment by gvigroux** [comment]
yes you're right. I changed the value to numerical because the HA translation system has changed and it was easier for me.
Now I understand your point :)

**Comment by gvigroux** [comment]
Values will stays numerical

**Comment by tomhanak** [comment]
Is there any technical reason (like getting these values directly from Haier) why the values must stay numerical?

It is not common. Consider e.g. ```sun.sun``` sensor that reports ```above_horizon``` value in state. That value is used directly in automations. But with your integration I must enter value ```7``` (instead of e.g. ```finished```) to trigger the automation. Additionally, supported values are not visible to the user, values are not sequential and some enums have values over 100 thus without looking at source code just trying to guess it by iterating from zero is really time consuming...

Having a text instead of a number also simplifies translations and helps fixing issues in translated text. Is each state translated correctly? Consider e.g. ```"7": "Ready"``` versus ```"finished": "Ready"```, in the later case the bug is obvious.

Would it be at least possible to add new attribute to these types of sensors like ```supported_states``` with all possible values? Similar to ```effect_list``` or ```supported_color_modes``` exposed by lights...

**Comment by itzsnyder** [comment]
Hey, is this a problem you can look into @gvigroux ? I am able to give you my credentials for a washing machine and dryer...

**Comment by gvigroux** [comment]
@tomhanak , @itzsnyder the numerical values are returned by the hOn server. 
After, I translate them into a string value in the UI. Of course the translation depends on the user language.

That's why I do prefer statys with the numerical value  (If I don't have the right translation, the real value will be showned)

**Comment by tomhanak** [comment]
If understand that you can't do much with numerical values returned by vendor and I didn't see the data yet.

But how do you know that e.g. above mentioned value ```7``` should be translated to English as "Finished"? There must be any clue in the raw vendor data.

What I was talking about is an intermediate layer converting raw vendor values and states to some internal names, usually English only "programmer" names, like ```above_horizon```. I can see various reasons why you didn't implement extra layer to keep the integration as simple as possible. And it's your choice.
But still, could you please re-consider it and improve user experience during automation configuration?
