### ISSUE TITLE
你好，想了解一下，这个插件的模板是在哪里下的？我也想开发一个。请教一下

### ISSUE THREAD

**Issue by dazhu6666** [gvigroux/hon#132]

**Comment by gvigroux** [comment]
can you please describe the issue ?

**Comment by willhaggan** [comment]
This is where you get the integraton and using this repo in Home Assistant will enable the HON compatiable devices. If you can please explain in English you may get more help. 

as per "gvigrouxc" HON repo homepage....


Installation

    Create a directory ‘hon’ containing the code of the custom_components/hon folder in your custom_components directory.
    OR you can add it through HACS > Integration > ... (top right) > Add custom depot > https://github.com/gvigroux/hon
    Restart HA
    Go to Settings - Devices and Services and Add integration. Search for hOn in search bar and select it
    Configure the integration with your hOn username and password
    Now you can see one new integration named with your email account with the entities and devices registered with hOn App. You can now add this entities in you panel
