### ISSUE TITLE
HA error 0.6.16

### ISSUE THREAD

**Issue by Theo16** [gvigroux/hon#133]
I have error after update to 0.6.16:

Rejestrator: py.warnings
Źródło: custom_components/hon/__init__.py:24
integracja: hOn (dokumentacja, Problemy)
Pierwsze zdarzenie: 14:28:55 (1 zdarzenia)
Ostatnio zalogowany: 14:28:55

/config/custom_components/hon/hon.py:163: SyntaxWarning: invalid escape sequence '\=' m = re.search('id_token\=(.+?)&', text)

**Comment by gvigroux** [comment]
sometimes the server replies strange thing. A reboot and everything should work agin.
