### ISSUE TITLE
Error and start /end time

### ISSUE THREAD

**Issue by anasiot** [gvigroux/hon#134]
Hello 

I have a  hon dryer machine and i‘ m Not able to catch error like when the water tank is full as this is not reported as error ,so i wanted to use start time > 5h so that‘s mean that is Stuck but this entité dies Not Return numeric, can you advise ?

**Comment by gvigroux** [comment]
Hi, this status is reported on the mobile hOn official app ?
can you please send a screenshot of all available values for your machine ?

**Comment by anasiot** [comment]
> Hi, this status is reported on the mobile hOn official app ? can you please send a screenshot of all available values for your machine ?

Hi, it’s reported as a notification pop up , these are the value

![IMG_5088](https://github.com/gvigroux/hon/assets/76408878/4b81ba29-b2ef-46e4-acd3-f0925a080597)

**Comment by gvigroux** [comment]
Did you checked if you can use "Program phase" for this ? Maybe the state you're looking for is a phase

**Comment by anasiot** [comment]
Phase refer to the program phases I checked when the water tank is full it’s still the same phase number

**Comment by gvigroux** [comment]
You should use the Program code to detect when the machine is starting and calculating the 5h
