### ISSUE TITLE
Erreur : Echec de la configuration

### ISSUE THREAD

**Issue by Magicpulse** [gvigroux/hon#137]
Bonjour,
J'ai une erreur depuis quelques jours dans l'intégration : Erreur : Echec de la configuration.
![image](https://github.com/gvigroux/hon/assets/88049271/b5fed452-011b-452c-b71b-3d55385a4242)

Tout fonctionnait bien jusqu'à présent.

J'ai désinstallé l'intégration, retéléchargé les sources : idem. Je me logge parfaitement sur mon appli et sur "https://account2.hon-smarthome.com/ "

J'ai 2 messages dans les logs : 
"Unable to retreive the frontdoor URL. Message: {"actions":[{"id":"79;a","state":"SUCCESS","returnValue":"Your login attempt has failed. Make sure the username and password are correct.","error":[]}],"context":
et
![image](https://github.com/gvigroux/hon/assets/88049271/e17db2c1-97c7-4c4b-9616-f113b3062b70)

Je suis sûr de mon password puisque je me logge sur "https://account2.hon-smarthome.com/" (j'ai vérifié plusieurs fois ma frappe, bien sûr).

Je suis en version 2024.6.0 (j'ai eu ce problème avant la montée de version).

**Comment by lechoooo** [comment]
Hi,
Got the exact same problem, checked the credentials several times and they should be good.
Problem first occurred this morning.
However in my case HON app is not responding to any commands, so perhaps HON cloud issue?

`Rejestrator: homeassistant.config_entries
Źródło: config_entries.py:594
Pierwsze zdarzenie: 09:15:18 (1 zdarzenia)
Ostatnio zalogowany: 09:15:18

Error setting up entry xxxxx@gmail.com for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/__init__.py", line 73, in async_setup_entry
    await coordinator.device.load_commands()
  File "/config/custom_components/hon/device.py", line 190, in load_commands
    self._appliance_model = commands.pop("applianceModel")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'applianceModel'`

**Comment by lechoooo** [comment]
Works again - as the HON cloud.
It was the HON side.

**Comment by gvigroux** [comment]
perfect :)
