### ISSUE TITLE
Problems to list devices

### ISSUE THREAD

**Issue by rodiebar** [gvigroux/hon#14]
Hello, after configure add-on in home assistant I have this error in log:

Logger: custom_components.hon.hon
Source: custom_components/hon/hon.py:172 
Integration: hOn 
First occurred: 20:11:19 (1 occurrences) 
Last logged: 20:11:19

Unable to get [id_token] during authorization process. Full response [......]

**Comment by rodiebar** [comment]
solved it by managing the account in salesforce.

**Comment by bitt86** [comment]
Turn off 2FA.
