### ISSUE TITLE
How do I update my hOn password?

### ISSUE THREAD

**Issue by marcingodlewski** [gvigroux/hon#145]
The hOn password expires after one year and needs to be changed. How do I enter the updated password in HomeAssistant without adding the integration from scratch? (I wouldn't want to make new integration as I'm afraid it could break existing dashboards, automations etc)
Thanks!

**Comment by 0rangutan** [comment]
Re-adding the integration won't break anything if you use the same name.

**Comment by gvigroux** [comment]
Yes, unfortunately it's the only option today, I didn't implement the password change yet
