### ISSUE TITLE
NodeRed no identifiers

### ISSUE THREAD

**Issue by nuker1991** [gvigroux/hon#146]
Hello, not sure if this is a bug or im doing it wrong but it seems right.
I get a nonetype for calling a service trough node red.

![afbeelding](https://github.com/user-attachments/assets/ea39c52b-f8d3-4567-aaa0-51ba102e965b)

![afbeelding](https://github.com/user-attachments/assets/ba80fa9d-314e-4a77-9ec2-8640225d3d3e)

Can someone tell me whats wrong ?

**Comment by gvigroux** [comment]
can you try by selecting an entity instead of a device?

**Comment by gvigroux** [comment]
Ok I found the problem, I will update soon

**Comment by gvigroux** [comment]
Should be fixed in 0.7.7
