### ISSUE TITLE
Washing mashine HW 28AMBS/1-S not visible in integration

### ISSUE THREAD

**Issue by TomasTrzil** [gvigroux/hon#16]
Hi, I´ve just bought new washing machine Hoover with hOn (HW 28AMBS/1-S),
Integration is installed, I´m logged in with my credentials, but my washing machine is not visible.  See: https://i.imgur.com/fymf0yn.png

HA restarted twice, nothing changed.

**Comment by TomasTrzil** [comment]
HA logs shows:

Logger: homeassistant.components.sensor
Source: custom_components/hon/cooler.py:27
Integration: Senzor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 11:00:52 (1 occurrences)
Last logged: 11:00:52

Error while setting up hon platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/hon/sensor.py", line 121, in async_setup_entry
    coordinator = HonCoolerCoordinator(hass, hon, appliance)
  File "/config/custom_components/hon/cooler.py", line 27, in __init__
    self._mac = appliance["macAddress"]
KeyError: 'macAddress'

**Comment by eximo84** [comment]
Same error using Hoover H-Wash 500 HW 411AMC/1-80

Any ideas how we can help get the data?

**Comment by ndom91** [comment]
Had this same issue, hOn is not reporting a mac address for one of the devices in your account.

In my case, I still had the default "virtual Wine rack" added in my account, which clearly isn't a physical device I own and so didn't have a mac address. This confused the integration.

Anyway, after removing the virtual wine rack from my account in the hOn app, rebooting HomeAssistant caused it to finally pick up my washing machine successfully.

**Comment by eximo84** [comment]
> Had this same issue, hOn is not reporting a mac address for one of the devices in your account.
> 
> 
> 
> In my case, I still had the default "virtual Wine rack" added in my account, which clearly isn't a physical device I own and so didn't have a mac address. This confused the integration.
> 
> 
> 
> Anyway, after removing the virtual wine rack from my account in the hOn app, rebooting HomeAssistant caused it to finally pick up my washing machine successfully.

This worked for me too. Stupid virtual wine cellar.

**Comment by TomasTrzil** [comment]
Perfect, thank you very much @ndom91 it worked. Really simple solution :-)

**Comment by gvigroux** [comment]
Everything has been fixed since :)
