### ISSUE TITLE
Support for  CSOE H9A2DE-S

### ISSUE THREAD

**Issue by maury77** [gvigroux/hon#17]
can I contribute ?

{"payload":{"resultCode":"0","shadow":{"parameters":{"drySynthMax":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"dryLevel":{"parNewVal":"2","lastUpdate":"2022-09-04T06:15:47Z"},"program21t":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program5t":{"parNewVal":"89","lastUpdate":"2022-09-03T14:14:13Z"},"program1t":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"dryCotton120":{"parNewVal":"4","lastUpdate":"2022-03-20T07:58:18Z"},"tumblingStatus":{"parNewVal":"0","lastUpdate":"2022-09-04T08:21:57Z"},"drySynthStore":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"machMode":{"parNewVal":"1","lastUpdate":"2022-09-04T08:21:57Z"},"checkUpStatus":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"errors":{"parNewVal":"00","lastUpdate":"2021-12-17T09:04:20Z"},"remoteCtrValid":{"parNewVal":"0","lastUpdate":"2022-09-04T06:15:47Z"},"program13t":{"parNewVal":"17","lastUpdate":"2022-01-30T17:07:37Z"},"dryCottonHang":{"parNewVal":"117","lastUpdate":"2022-09-04T08:14:50Z"},"anticrease":{"parNewVal":"1","lastUpdate":"2022-09-03T08:27:56Z"},"doorStatus":{"parNewVal":"1","lastUpdate":"2022-09-05T18:51:20Z"},"program17t":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"hybrid":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"remainingTimeMM":{"parNewVal":"150","lastUpdate":"2022-09-04T08:21:57Z"},"opt5":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"dryingManager":{"parNewVal":"1","lastUpdate":"2022-09-03T08:27:56Z"},"bestIroning":{"parNewVal":"0","lastUpdate":"2022-02-04T13:57:55Z"},"opt8":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"opt6":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program10t":{"parNewVal":"46","lastUpdate":"2022-08-29T22:41:57Z"},"opt7":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program4":{"parNewVal":"6","lastUpdate":"2022-08-28T21:34:56Z"},"program3":{"parNewVal":"65","lastUpdate":"2022-09-04T08:14:50Z"},"program6t":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program6":{"parNewVal":"14","lastUpdate":"2022-07-22T00:51:02Z"},"drySynthHang":{"parNewVal":"1","lastUpdate":"2022-04-30T12:39:23Z"},"program5":{"parNewVal":"42","lastUpdate":"2022-09-03T14:14:13Z"},"program8":{"parNewVal":"4","lastUpdate":"2022-03-20T07:58:18Z"},"program7":{"parNewVal":"5","lastUpdate":"2022-07-29T22:29:10Z"},"program2t":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program9":{"parNewVal":"21","lastUpdate":"2022-08-29T21:44:16Z"},"dryCottonStore":{"parNewVal":"2","lastUpdate":"2022-06-27T12:40:06Z"},"dryCotton60":{"parNewVal":"72","lastUpdate":"2022-09-04T00:21:25Z"},"drySynth120":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program2":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program1":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"dryCottonMax":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"prCode":{"parNewVal":"0","lastUpdate":"2022-09-04T00:21:25Z"},"program14t":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program18t":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program19":{"parNewVal":"16","lastUpdate":"2022-09-04T00:21:25Z"},"dryCottonBone":{"parNewVal":"7","lastUpdate":"2022-08-28T21:34:56Z"},"dryCotton180":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program18":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program17":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"prPhase":{"parNewVal":"0","lastUpdate":"2022-09-04T08:14:50Z"},"program16":{"parNewVal":"2","lastUpdate":"2022-02-04T16:28:23Z"},"program11t":{"parNewVal":"31","lastUpdate":"2022-05-22T06:12:41Z"},"dryCottonIron":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program11":{"parNewVal":"33","lastUpdate":"2022-07-29T05:30:04Z"},"program10":{"parNewVal":"11","lastUpdate":"2022-08-29T22:41:57Z"},"program7t":{"parNewVal":"0","lastUpdate":"2022-07-29T22:29:10Z"},"program15":{"parNewVal":"1","lastUpdate":"2022-06-27T12:40:06Z"},"program14":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program13":{"parNewVal":"1","lastUpdate":"2022-01-30T17:07:37Z"},"waterTankStatus":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program12":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program3t":{"parNewVal":"105","lastUpdate":"2022-09-04T08:14:50Z"},"dryFilterStatus":{"parNewVal":"0","lastUpdate":"2022-09-04T08:21:57Z"},"program8t":{"parNewVal":"72","lastUpdate":"2022-03-20T07:58:18Z"},"dryLevelMgmt":{"parNewVal":"1","lastUpdate":"2022-09-04T08:02:23Z"},"program15t":{"parNewVal":"67","lastUpdate":"2022-06-27T12:40:06Z"},"program19t":{"parNewVal":"7","lastUpdate":"2022-09-04T00:21:25Z"},"delayTime":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"dryTime":{"parNewVal":"0","lastUpdate":"2022-05-16T12:23:25Z"},"prPosition":{"parNewVal":"1","lastUpdate":"2022-09-07T14:00:04Z"},"program12t":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program20t":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program4t":{"parNewVal":"79","lastUpdate":"2022-08-28T21:34:56Z"},"program21":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program20":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"drySynth60":{"parNewVal":"15","lastUpdate":"2022-07-29T22:29:10Z"},"program9t":{"parNewVal":"60","lastUpdate":"2022-08-29T21:44:16Z"},"drySynthIron":{"parNewVal":"3","lastUpdate":"2022-02-04T13:57:40Z"},"drySynth180":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"},"program16t":{"parNewVal":"70","lastUpdate":"2022-02-04T16:28:23Z"},"drySynthBone":{"parNewVal":"0","lastUpdate":"2021-12-17T09:04:20Z"}}},"activity":{},"commandHistory":{"command":{"macAddress":"c4-4f-33-32-b6-4d","commandName":"startProgram","applianceOptions":{"opt1":"anticrease","opt2":"dryingManager","opt3":"bestIroning","opt4":"hybrid"},"programName":"PROGRAMS.TD.IOT_DRY_BATHROBE","ancillaryParameters":{"remoteActionable":"1","functionalId":"9","remoteVisible":"1","suggestedLoadD":"6","programCluster":"specialCare","energyLabel":"0","programFamily":"[download|guided]","programRules":{"opt3":{"dryLevel":{"2|3|4":{"fixedValue":"0","typology":"fixed"}}},"dryTime":{"dryTimeMM":{"30":{"fixedValue":"1","typology":"fixed"},"45":{"fixedValue":"2","typology":"fixed"},"59":{"fixedValue":"3","typology":"fixed"},"70":{"fixedValue":"4","typology":"fixed"},"80":{"fixedValue":"5","typology":"fixed"},"90":{"fixedValue":"6","typology":"fixed"},"100":{"fixedValue":"7","typology":"fixed"},"110":{"fixedValue":"8","typology":"fixed"},"120":{"fixedValue":"9","typology":"fixed"},"130":{"fixedValue":"10","typology":"fixed"},"140":{"fixedValue":"11","typology":"fixed"},"150":{"fixedValue":"12","typology":"fixed"},"160":{"fixedValue":"13","typology":"fixed"},"170":{"fixedValue":"14","typology":"fixed"},"180":{"fixedValue":"15","typology":"fixed"},"190":{"fixedValue":"16","typology":"fixed"},"200":{"fixedValue":"17","typology":"fixed"},"210":{"fixedValue":"18","typology":"fixed"},"220":{"fixedValue":"19","typology":"fixed"}}},"dryLevel":{"opt3":{"1":{"fixedValue":"1","typology":"fixed"}}}}},"applianceType":"TD","attributes":{"prStr":"Accappatoi e Spugne","channel":"mobileApp","energyLabel":"0","origin":"standardProgram"},"device":{"appVersion":"1.46.4","deviceModel":"iPhone13,3","osVersion":"15.6.1","mobileId":"49106874-D9ED-4268-8343-7B183B1373D6","mobileOs":"ios"},"parameters":{"dryingManager":"1","hybrid":"0","steamLevel":"0","checkUpStatus":"0","anticrease":"1","delayTime":"0","prCode":"35","prPosition":"19","dryLevel":"0","bestIroning":"0","onOffStatus":"1"},"transactionId":"c4-4f-33-32-b6-4d_2022-09-03T19:57:17.248Z","timestamp":"2022-09-03T19:57:17.248Z"},"timestampAccepted":"2022-09-03T19:57:18.5Z","timestampExecuted":"2022-09-03T19:57:19.7Z"},"lastConnEvent":{"macAddress":"c4-4f-33-32-b6-4d","category":"DISCONNECTED","instantTime":"2022-09-07T14:05:30Z","timestampEvent":1662559530266}},"authInfo":{}}

**Comment by gvigroux** [comment]
AFAIK, nobody has integrated yet a tumble drier :(
It's very difficult to do it without machine access.

**Comment by gvigroux** [comment]
I just realized the support has been added :) 
Can you test ?

**Comment by maury77** [comment]
this is the situation

![image](https://user-images.githubusercontent.com/35746732/224651957-2572fbde-3d3b-4a4a-903f-5111f8536bc0.png)

From log there is

mar 13 09:51:30 sdomotica Home Assistant[1071]: 2023-03-13 09:51:30.112 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
mar 13 09:51:30 sdomotica Home Assistant[1071]: Traceback (most recent call last):
mar 13 09:51:30 sdomotica Home Assistant[1071]:   File "/home/homeassistant/.pyenv/versions/3.10.9/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
mar 13 09:51:30 sdomotica Home Assistant[1071]:     await self._async_refresh(log_failures=True, scheduled=True)
mar 13 09:51:30 sdomotica Home Assistant[1071]:   File "/home/homeassistant/.pyenv/versions/3.10.9/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
mar 13 09:51:30 sdomotica Home Assistant[1071]:     self.async_update_listeners()
mar 13 09:51:30 sdomotica Home Assistant[1071]:   File "/home/homeassistant/.pyenv/versions/3.10.9/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
mar 13 09:51:30 sdomotica Home Assistant[1071]:     update_callback()
mar 13 09:51:30 sdomotica Home Assistant[1071]:   File "/mnt/dietpi_userdata/homeassistant/custom_components/hon/sensor.py", line 733, in _handle_coordinator_update
mar 13 09:51:30 sdomotica Home Assistant[1071]:     self._on = json["onOffStatus"]["parNewVal"] == "1"

**Comment by gvigroux** [comment]
The bus is still there?
