### ISSUE TITLE
Add support to change Wine Cooler light on/off

### ISSUE THREAD

**Issue by TroLoos** [gvigroux/hon#28]
Hi, first of all - thank you for your great work, I was really surprised that my recently purchased Wine Cooler (HWS42GDAU1) is actually supported by this component 👍

It works great - I can read all the sensors:

<img width="326" alt="Screenshot 2022-11-09 at 00 35 50" src="https://user-images.githubusercontent.com/24640072/200699041-851e5d90-8dee-481d-9e43-524d3021a225.png">

What it would make it even better - if it was possible to turn the light on and off from within HA. It would be a great addition to lighting automations (you enter the room, wine cooler's light goes on...).

If there's anything I can do here to help, just let me know (basic programming experience).

**Comment by gvigroux** [comment]
Hi, I've added a generic ligh service in this repo: https://github.com/gvigroux/hon/tree/Full-rework
Can you try ?

**Comment by TroLoos** [comment]
Unfortunately, there are still no entities that could be switched on/off:
<img width="334" alt="Screenshot 2023-03-22 at 18 48 22" src="https://user-images.githubusercontent.com/24640072/226993712-8f844104-7d4f-48fb-b12a-c626e1255544.png">
It did change comparing to previous version:
<img width="329" alt="Screenshot 2023-03-22 at 18 54 28" src="https://user-images.githubusercontent.com/24640072/226994781-ec7e2c4e-39c2-4f2c-b2ba-5a66cc63fdb4.png">
but all the entities are still sensors, light did not change to switch.

Thanks a lot for trying though :-). I'm sure it can be done, and I am ready to help testing.

**Comment by gvigroux** [comment]
I've updated the main branch so you can try from there.
You have 2 services to start and stop the lights :) but it's still not a button.

**Comment by TroLoos** [comment]
> I've updated the main branch so you can try from there.
> You have 2 services to start and stop the lights :) but it's still not a button.

What a great support! ;-)

Indeed, there are services to be called, I've checked hon.turn_light_on and it works flawlessly. Looks like turn_light_off still needs a little bit of tweak, it doesn't do anything. Can you have a second look at it? Perhaps I can send a custom request but I don't know the schema to follow.

**Comment by gvigroux** [comment]
OUPS, light_off should works now :)

**Comment by TroLoos** [comment]
@gvigroux thank you a million!

I'm waiting for a change to propagate :-).

**Comment by gvigroux** [comment]
Done! Sorry it was stuck on my side

**Comment by TroLoos** [comment]
@gvigroux I'm going to say that again - what a support!

Everything works like a charm :-).

You can add it to fully supported list:

Device info
HWS42GDAU1
by haier
Firmware: 5.12.0

**Comment by gvigroux** [comment]
Thanks :)

**Comment by TroLoos** [comment]
@gvigroux I'm not sure when exactly, but this service (light on/off) stopped working with unknown error. Are there any information that I could provide to help you figure it out why it's not working?

Tried from NodeRed ("Call-service error. cannot access local variable 'json' where it is not associated with a value") and Developer Tools in HA ("Failed to call service hon.turn_light_on. Unknown error").

I'm on the newest available version of the add on.

**Comment by gvigroux** [comment]
Let me look at it

**Comment by gvigroux** [comment]
@TroLoos, it should work again now :) Can you please test ?

**Comment by TroLoos** [comment]
@gvigroux yes, you got it right! Works like a charm again.

Thank you!

**Comment by gvigroux** [comment]
Perfect :)
