### ISSUE TITLE
Integration is losing connection with airco/api

### ISSUE THREAD

**Issue by MarkKlerkx** [gvigroux/hon#29]
Hello,

Once a week the integration is not responding on the automation to start the airco.
I think that the connection between the integration and the h0n api is list.

Normally I would reload the integration in the UI, but in this case I need to restart HA.

**Comment by arjanvanleent** [comment]
Got the same problem

**Comment by gvigroux** [comment]
Should be fix

**Comment by MarkKlerkx** [comment]
Unfortenutaly, the issue is not solved.
Is it possible to add an option to reload the integration? Than I can schedule a nightly reload. I do this with more integrations with similar problems.

Thanks!!

**Comment by gvigroux** [comment]
@MarkKlerkx , what is the error in the logs?

**Comment by MarkKlerkx** [comment]
Hello, i just activated the debugging
As soon as the problem appears, I will have a look.
I assume that everything is recorded in the HA Core log. Is that right?

Grtz,

Mark

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gvigroux** [comment]
Perfect :)
