### ISSUE TITLE
[FEATURE REQUEST] windDirectionVertical/Horizontal exposed as attributes

### ISSUE THREAD

**Issue by pawelsky** [gvigroux/hon#31]
Hi @gvigroux  I've been looking for this kind of integration for quite a while and I'm happy I've finally found someone working on it, great work!

I'm using two AS25S2SF1FA-WH in 2x1 configuration and so far I've been using SmartIR integration with generated set of IR codes which worked great but gave me feedback about current state of the devices.

After installing your integration everything works great, devices were auto discovered, can be controlled without problems and the state changes are visible regardless of whether I control the units via HA, hOn app or IR remote, just what I needed!

There is however one big thing that I'm missing - namely the ability to independently control windDirectionVertical and windDirectionHorizontal. I can see that they are now controlled by swing mode (set to medium if the swing in given direction is set to off) but it would be great if they were exposed as separate attributes (plus services to change them) so they could be controlled independently of the swing mode.

Would you consider adding such feature?

**Comment by gvigroux** [comment]
Hi, I just did it :) Can you please check and create another issue in case of problem ?
