### ISSUE TITLE
Unable to get [id_token] during authorization process

### ISSUE THREAD

**Issue by DeimicUser** [gvigroux/hon#32]
Hi
Working with hon integration in HA works ok but always between 1am-5am I receive error in logs:
"Unable to get [id_token] during authorization process"
Because of that current temperature is not correct when I'm checking this in HA. After run of airconditioner actual temperature is correct. Full log below:
Unable to get [id_token] during authorization process. Full response [ <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> <html> <head> <meta HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE"> <script> function redirectOnLoad()
Unable to get the state of the hOn device. HTTP code: 403 and text[{"Message":"User is not authorized to access this resource with an explicit deny"}]

**Comment by stochlinski** [comment]
Hello, I have the same problem. From time to time my Hon integration stoped comunicate with my Haier Climate and in logs I can found above messages.

**Comment by stochlinski** [comment]
I have HA 2022.11.1, I thing before I didn't have this problems.

**Comment by kelo77** [comment]
I have the same problem starting after updating HA. Now i run  2022.11.2. It temporary fix if i restart HA

**Comment by Argosy87** [comment]
If you disable the 2-factor authentication it works.

**Comment by stochlinski** [comment]
> If you disable the 2-factor authentication it works.

2-factor of which application? My Hon never have activated this.

**Comment by psypher5** [comment]
Don't know if this is any help, but I have just experienced this:

(im UK based)
Hon app is working with my washing machine, 
NOTE: 2fa is OFF, I never set this up.


Setup integration in HA, restart a bunch of times and no devices, nothing.
Log spits an unable to get ID token error which mentioned something around this url: https://he-accounts.force.com/SmartHome

so I went to https://he-accounts.force.com/SmartHome/s/login on desktop, and it prompted a password change, which i did.
Takes me to a CANDY page where i can click my account, and it had my details correct (doesnt show any device info etc there, just account info it seems)
This emailed me a verification code for 2fa (which i know i never set up)
Went onto the hon app > account and 2fa was turned on
Turned it off
Restarted HA and device appeared

**Comment by gvigroux** [comment]
Thanks for sharing this experience, can be useful for others.
I will close this issue for now. Let's see if someone else has a problem

**Comment by and7ey** [comment]
I was having the same issue - Unable to get [id_token]. Some devices were added before and stopped working. I was choosing Add Entry and trying to add the same account there second time. The result window shows nothing (and it should be fixed!). I've deleted the account within this addon and added it again, it helped to resolve the problem.
