### ISSUE TITLE
Add hOn Logo

### ISSUE THREAD

**Issue by jangelgon** [gvigroux/hon#34]
To have the hOn integration located by its logo in the integrations window.
https://developers.home-assistant.io/blog/2020/05/08/logos-custom-integrations/

Logo repo
https://github.com/home-assistant/brands/tree/master/custom_integrations

**Comment by gvigroux** [comment]
I just did a PR for that.
https://github.com/home-assistant/brands/pull/4185
Let's see if it goes through

**Comment by gvigroux** [comment]
My request was rejected because it must be a brand logo. Someone sent the "Haier" logo for this integration. I think it should be more "Candy" because it's the group name, but at least we have an icon now :).
