### ISSUE TITLE
Add Candy refrigerator Model CCE4T620EB

### ISSUE THREAD

**Issue by chodorenko** [gvigroux/hon#41]
Please Add Candy refrigerator Model CCE4T620EB

Logger: custom_components.hon
Source: custom_components/hon/__init__.py:60
Integration: hOn
First occurred: 12:51:37 (1 occurrences)
Last logged: 12:51:37

Unknown device detected [{'fwVersion': '3.8.0', 'applianceTypeId': 14, 'firstEnrollment': False, 'attributes': [{'parValue': '03.12.00', 'id': 98537740, 'parName': 'acuVersion', 'status': 1, 'lastUpdate': '2023-02-01T09:46:32Z'}, {'parValue': 'ESP32D0WDQ5', 'id': 98537739, 'parName': 'chipset', 'status': 1, 'lastUpdate': '2023-02-01T09:46:32Z'}, {'parValue': '167', 'id': 98538146, 'parName': 'dictionaryId', 'status': 1, 'lastUpdate': '2023-02-01T09:48:21Z'}, {'parValue': 'it-IT', 'id': 98537738, 'parName': 'lang', 'status': 1, 'lastUpdate': '2023-02-01T09:46:32Z'}], 'applianceModelId': 813, 'series': 'romania', 'firstEnrollmentTBC': False, 'code': '34004960', 'SK': 'app#34-86-xx-xx-34-90', 'macAddress': '34-86-xx-xx-34-90', 'eepromName': 'no_eeprom', 'applianceId': '34-86-xx-xx-34-90#2023-02-01T09:46:20Z', 'id': 813, 'modelName': 'CCE4T620EB', 'applianceTypeName': 'REF', 'connectivity': 'wifi|ble', 'serialNumber': '340xxxxxxxx094', 'enrollmentDate': '2023-02-01T09:46:20.530Z', 'brand': 'candy', 'lastUpdate': '2023-02-01T09:46:32Z', 'eepromId': 41, 'applianceStatus': 1, 'coords': {'lng': 23.1265361, 'lat': 53.1144253}, 'PK': 'user#eu-west-1:75acd8ec-2457-47e8-82ef-d04bbbad9f72', 'sections': {'chatbot': True, 'epp_enabled': True, 'double_pairing_hidden': True}, 'topics': {'publish': [], 'subscribe': ['$aws/events/presence/disconnected/34-86-xx-xx-34-90', '$aws/events/presence/connected/34-86-xx-xx-34-90', 'haier/things/34-86-xx-xx-34-90/event/appliancestatus/update', 'haier/things/34-86-xx-xx-34-90/event/discovery/update']}}] with latest status [{'payload': {'resultCode': '0', 'shadow': {'parameters': {'quickModeZ1': {'parNewVal': '0', 'lastUpdate': '2023-02-01T09:37:54Z'}, 'intelligenceMode': {'parNewVal': '1', 'lastUpdate': '2023-02-01T09:50:05Z'}, 'quickModeZ2': {'parNewVal': '0', 'lastUpdate': '2023-02-01T09:37:54Z'}, 'tempSelZ2': {'parNewVal': '-20', 'lastUpdate': '2023-02-01T09:37:54Z'}, 'holidayMode': {'parNewVal': '0', 'lastUpdate': '2023-02-01T09:37:54Z'}, 'tempSelZ1': {'parNewVal': '4', 'lastUpdate': '2023-02-01T09:37:54Z'}, 'errors': {'parNewVal': '00', 'lastUpdate': '2023-02-01T09:49:16Z'}, 'tempEnv': {'parNewVal': '21', 'lastUpdate': '2023-02-01T09:47:21Z'}, 'sterilizationStatus': {'parNewVal': '1', 'lastUpdate': '2023-02-01T09:37:54Z'}, 'doorStatusZ1': {'parNewVal': '0', 'lastUpdate': '2023-02-01T09:50:20Z'}}}, 'activity': {}, 'commandHistory': {'command': {'macAddress': '34-86-xx-xx-34-90', 'commandName': 'startProgram', 'applianceOptions': {}, 'ancillaryParameters': {'programRules': {'fixedValue': {'tempSelZ1': {'@quickModeZ1': {'1': {'fixedValue': '1', 'typology': 'fixed'}}, '@intelligenceMode': {'1': {'fixedValue': '5', 'typology': 'fixed'}}, '@holidayMode': {'1': {'fixedValue': '17', 'typology': 'fixed'}}, '@quickModeZ2': {'1': {'fixedValue': '@tempSelZ1', 'typology': 'fixed'}}}, 'tempSelZ2': {'@quickModeZ1': {'1': {'fixedValue': '@tempSelZ2', 'typology': 'fixed'}}, '@intelligenceMode': {'1': {'fixedValue': '-18', 'typology': 'fixed'}}, '@holidayMode': {'1': {'fixedValue': '@tempSelZ2', 'typology': 'fixed'}}, '@quickModeZ2': {'1': {'fixedValue': '-24', 'typology': 'fixed'}}}}, 'typology': 'fixed', 'category': 'rule', 'mandatory': 0}}, 'applianceType': 'REF', 'attributes': {'prStr': 'PROGRAMS.REF.AUTO_SET', 'channel': 'mobileApp', 'origin': 'standardProgram'}, 'device': {'appVersion': '1.51.9', 'deviceModel': 'sdm845', 'osVersion': '29', 'mobileId': '814efd566ca3456a', 'mobileOs': 'android'}, 'parameters': {'intelligenceMode': '1'}, 'transactionId': '34-86-xx-xx-34-90_2023-02-01T09:49:58.494Z', 'timestamp': '2023-02-01T09:49:58.493Z'}, 'timestampAccepted': '2023-02-01T09:50:01.1Z', 'timestampExecuted': '2023-02-01T09:50:02.1Z'}, 'lastConnEvent': {'macAddress': '34-86-xx-xx-34-90', 'category': 'CONNECTED', 'instantTime': '2023-02-01T09:49:09Z', 'timestampEvent': 1675244949030}}, 'authInfo': {}}]

**Comment by chodorenko** [comment]
@gvigroux you can add it device ? I can help You ?

**Comment by gvigroux** [comment]
I've added a first basic version of the fridge support but I'm in the dark (I don't have one).
If you can send me your hOn login/password I can do the full integration => of course you will have to change the password before/after

**Comment by chodorenko** [comment]
Now i view my fridge as 
![image](https://user-images.githubusercontent.com/18162420/224696427-15fee714-2102-4724-95ff-65dda49003d0.png)

Please Give You contact as email/telegram/skype or different for send login and pass for you tests

**Comment by gvigroux** [comment]
@chodorenko : great at least it doesn't crash :)
You can send me details to gvigroux@free.fr, I will have time to really develop only at the end of this week so I don't plan to test before.

**Comment by chodorenko** [comment]
@gvigroux  Send Access to Email

**Comment by gvigroux** [comment]
I've added all possible sensors now. Can you please try to change all status from the mobile app and tells me which sensor you can update ? (all list of possible values)
- IntelligenceMode
- Quick Mode Zone 1
- Quick Mode Zone 2
- Holiday Mode
- Sterilization Status
