### ISSUE TITLE
Connection is lose after some period

### ISSUE THREAD

**Issue by Cosik** [gvigroux/hon#42]
Hi,

I noticed that data is not refreshed on my HA so I tried to turn on my Haier AC (AS35S2SF1FA-WH) but get error:

  Logger: homeassistant.components.websocket_api.http.connection
  Source: custom_components/hon/hon.py:310
  Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
  First occurred: 10:29:06 (2 occurrences)
  Last logged: 17:01:55
  
      [547902262432] 'payload'
      [547786899856] 'payload'
  
  Traceback (most recent call last):
    File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
      await hass.services.async_call(
    File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
      task.result()
    File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
      await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
    File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
      await service.entity_service_call(
    File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
      future.result()  # pop exception if have
    File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
      await coro
    File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
      await result
    File "/config/custom_components/hon/climate.py", line 368, in async_set_hvac_mode
      await self.async_send_command(command)
    File "/config/custom_components/hon/climate.py", line 404, in async_send_command
      await self._hon.async_set(self._mac, self._typeName, self.get_command(parameters))
    File "/config/custom_components/hon/hon.py", line 310, in async_set
      if json_data["payload"]["resultCode"] == "0":
  KeyError: 'payload'

More logs:
`Unable to get [id_token] during authorization process. Full response [ <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> <html> <head> <meta HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE"> <script> function redirectOnLoad() { var escapedHash = ''; var url = 'https://he-accounts.force.com/SmartHome/s/login?display=touch&ec=302&inst=68&startURL=%2FSmartHome%2Fsetup%2Fsecur%2FRemoteAccessAuthorizationPage.apexp%3Fsource%3DCAAAAYZV0XqBMDAwMDAwMDAwMDAwMDAwAAAA8pGUkKuWuKyNqdsbLRQEuNarnxsn4IvKjkogYPvjpVbZs22XPkuGKR8-vqi5WUypPnppdgehF0WJAY9dxN811Q9XwX3C_J_8iJJ2uTr3J8ICbzJRtSe6aiKhT0ARj-tDr8QrH2eoaQUth5zisETGBKKt9_hZ40U4lGcf3rOtVUNXlXZK55hMOiqnOQA27AOBEp8bseejA11E5T-LWDTtKE_JjXw0J6UJBUUBt8eVUh6RU89haFjyLHfQz1FnDUu40uZAOutw08OpLx-jQXtLkS3pmAxFkrZhjNoYVbaUsYfSQmkvs5EeC9K311Fo1nvQ8w43zLLsvhI3nc1IuSmbNq6MXHa8ZMxNKT730TxbazAIHIe6-3R5JqLH2dJKgcVmImDh2B-bDo0TkWNv-gr0b0WJ4FV8VINUF2YhAA-cl_AmSXjkOVs7-cu0Yt17iV8K5kHgMHkdvB9TQwAI8HU4k-kalPRYnaN-_XMT4s0x8L4nsSS71UNNtkEAHeWJCbOVGuvsH9BfYzxJnf6Qq0lH2jGkWj6HlZ3OqogYGswFZrexPo-R5rs9xvAr1mASfR5mLN55zRtoYzj8xHE8EWY-PG2z7f50Wuh99xp1isTr9I5EarrLh-z0A8fFmwhnYzDaYWj3Zx_xHZTyjX-J9CpvDRdETCI92UjIRACFG3RDBYw5hl4vTWf43mcIZxYdUQTbov6fw2P9SuOgrDUbvnGWIE4%253D%26display%3Dtouch'; if (window.location.hash) { escapedHash = '%23' + window.location.hash.slice(1); } if (window.location.replace){ window.location.replace(url + escapedHash); } else { window.location.href = url + escapedHash; } } redirectOnLoad(); </script> </head> </html> ]
Unable to get [id_token] during authorization process. Full response [ <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> <html> <head> <meta HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE"> <script> function redirectOnLoad() { var escapedHash = ''; var url = 'https://he-accounts.force.com/SmartHome/s/login?display=touch&ec=302&inst=68&startURL=%2FSmartHome%2Fsetup%2Fsecur%2FRemoteAccessAuthorizationPage.apexp%3Fsource%3DCAAAAYZXiUx6MDAwMDAwMDAwMDAwMDAwAAAA8peCfC6evM5tRXiQzuhqidDbJGt3UH_2PdchKUA9fkW-Orr64AhxuYiblFn9evzOBNZ0iMJy1jHJc8kVAZJxG2P4TqXosxtGG8x6CqpPidVixb3xgXFL-Rjp7DQMm44RbUjRouPh7zGEjKii66xENOL8x_THcrhWOZjXGj1cWW4aGdQHgna15Rdy6QFKKxq86jZyFN3tCn0TK7vLCyPKPxa98IFFkQCoGxPOGuhPnyUYNLrtBfk2H2yYLPfOyXvTm-bqkWo0EqaRxPyrKBrG0NW_am7CIrPJxu-kVfxBSmXg-7C-Ovk-GwQ77O6llLggXSIHK6m2lDdcMWrsxE-LTzRCZwm38MIXBI3F0OF8qa87gGtJlEl-k7_DTKXW1zpXld-kzak9LjYGjiM2Gd3EtXmBL5HOC6lCc0cy0HgvbnUzPcDQagutVUp2K9DXXi0q268pYveARBw6hohZxrBmW7zU3zn5wDeTadEzV0GHHmcnwvZotqtRzOUQio9RYZwacaXnquPgiszJY7vC6F_21bM8e3tGj1wBRyK9LDnwVoS7-YjrztG21r95PWROlY806F3zzyUM9syqIZ55wdKI6liIiHEFcsdmJGc5zPJJIrEPsUDCdAz64U4wZEiGqp4a_AMzS-oA0KnMG-OFElEWjt02WQd647kffV76CR5Bmhkvo9Am9hI3z_HuqKTF5xro4KUfJxEcy-gPwPo2Fy4oYVo%253D%26display%3Dtouch'; if (window.location.hash) { escapedHash = '%23' + window.location.hash.slice(1); } if (window.location.replace){ window.location.replace(url + escapedHash); } else { window.location.href = url + escapedHash; } } redirectOnLoad(); </script> </head> </html> ]
Unable to get the state of the hOn device. HTTP code: 403 and text[{"Message":"User is not authorized to access this resource with an explicit deny"}]
Unable to get [id_token] during authorization process. Full response [<body><form accept-charset="UTF-8" action="hon://mobilesdk/detect/oauth/done#access_token=00DU0000000Lkcq%21ARUAQIPxgEUFwLYnOAgOoTPKNoxlyFdM_1P7qehVkrm60dXCNFIXMUboldhDLH55ilu4YaKWh0v1L43pszEgxkth_ZNr1bks&amp;refresh_token=5Aep861ikNsOLQGnboERb071AJnH78LQeRc565OaERZ5WAJq7ns8SlGC6e1duM2V_vF4nEoTVuGwtvufdexmqiJ&amp;instance_url=https%3A%2F%2Fhaiereurope.my.salesforce.com&amp;id=https%3A%2F%2Flogin.salesforce.com%2Fid%2F00DU0000000LkcqMAC%2F00568000004eqQZAAY&amp;issued_at=1676419477569&amp;signature=kM3GHGfECiVZmYfu86rWsHHKpuZbwKPhzSX6hWj6VVQ%3D&amp;sfdc_community_url=https%3A%2F%2Fhe-accounts.force.com%2FSmartHome&amp;sfdc_community_id=0DB4O000000U1KVWA0&amp;id_token=eyJraWQiOiIyNDIiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoidE1KYm9ONlM2TXVXSzk5OGVpVHpJUSIsInN1YiI6Imh0dHBzOi8vbG9naW4uc2FsZXNmb3JjZS5jb20vaWQvMDBEVTAwMDAwMDBMa2NxTUFDLzAwNTY4MDAwMDA0ZXFRWkFBWSIsInpvbmVpbmZvIjoiRXVyb3BlL1ByYWd1ZSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhZGRyZXNzIjp7fSwicHJvZmlsZSI6Imh0dHBzOi8vaGFpZXJldXJvcGUubXkuc2FsZXNmb3JjZS5jb20vMDA1NjgwMDAwMDRlcVFaQUFZIiwiaXNzIjoiaHR0cHM6Ly9oZS1hY2NvdW50cy5mb3JjZS5jb20vU21hcnRIb21lIiwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VudHlyei5tQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJNaWNoYcWCIiwibG9jYWxlIjoicGwiLCJub25jZSI6IjgyZTlmNGQxLTE0MGUtNDg3Mi05ZmFkLTE1ZTI1ZmJmMmI3YyIsInBpY3R1cmUiOiJodHRwczovL2hlLWFjY291bnRzLmZvcmNlLmNvbS9pbWcvdXNlcnByb2ZpbGUvZGVmYXVsdF9wcm9maWxlXzIwMF92Mi5wbmciLCJjdXN0b21fYXR0cmlidXRlcyI6eyJQcml2YWN5VXBkYXRlZCI6InRydWUiLCJQZXJzb25Db250YWN0SWQiOiIwMDM2ODAwMDAwSk9LUUhBQTUiLCJKV1QiOiIiLCJFeHRlcm5hbFNvdXJjZSI6IklvVCBNb2JpbGUgQXBwIiwiRXh0ZXJuYWxTdWJTb3VyY2UiOiJoT24iLCJQZXJzb25BY2NvdW50SWQiOiIwMDE2ODAwMDAwTks2SDVBQUwiLCJDb3VudHJ5IjoiUEwiLCJVc2VyTGFuZ3VhZ2UiOiJwbCJ9LCJhdWQiOiIzTVZHOVFEeDhJWDhuUDVUMkhhOG9mdmxtakxabDVMX2d2ZmJUOS5ISnZwSEdLb0FTX2RjTU44TFlwVFNZZVZGQ3JhVW5WLjJBZzFLaTdtNHpuVk82LG15bW9iaWxlYXBwOi8vY2FsbGJhY2ssY2FuZHk6Ly9tb2JpbGVzZGsvZGV0ZWN0L29hdXRoL2RvbmUsaG9vdmVyOi8vbW9iaWxlc2RrL2RldGVjdC9vYXV0aC9kb25lLHJvc2llcmVzOi8vbW9iaWxlc2RrL2RldGVjdC9vYXV0aC9kb25lLGhvbjovL21vYmlsZXNkay9kZXRlY3Qvb2F1dGgvZG9uZSxodHRwczovL2FwcC5nZXRwb3N0bWFuLmNvbS9vYXV0aDIvY2FsbGJhY2ssIiwidXBkYXRlZF9hdCI6IjIwMjMtMDEtMjZUMTI6MTE6NDFaIiwibmlja25hbWUiOiJVc2VyMTY3NDczNDQ5OTU2NDMwMDgyODMiLCJuYW1lIjoiTWljaGHFgiBTZW50eXJ6IiwicGhvbmVfbnVtYmVyIjpudWxsLCJleHAiOjE2NzY0NDgyNzcsImlhdCI6MTY3NjQxOTQ3NywiZmFtaWx5X25hbWUiOiJTZW50eXJ6IiwiZW1haWwiOiJzZW50eXJ6Lm1AZ21haWwuY29tIn0.N3SGoZwVriEmCrmrIQ1cRflUWErOLPeubdYYuuuB2hADaL40qg6bhfWT64mGsWDj-UGL219YwzraYZ6MNGdpmhITGyA3hTUA9EXr3CPYRj1D0UuRkbiaw1csh5Tvump87VcKANjWtE6d8uHV9P8sTfpwz8Cd9NeNVxwVVbVQXXMK-cw4pKIb8n-NmYFI22kwFiFizqFDkBeBueaF0cuBn0H3UlBiAl54_fVRc-8t0lxYSmv_p0LsStOA-vJ3L03MA-HxBLjBKt6I7YmnDNsu8aCUimtqumk8ctdHMNU_fT1it0Hd89UUc27XfhfNWP3H78KGv6asjumWxkINeZCve9x-qDZ0-Mrg52phgDhGWQqrNi_eBShA00DHkM-8eZ0RbpWOoBog3s3BcIugbLJ5m5pll8c7g9Ecj_Ivqm4ubbK3art6gRj3drhn6rD06I1gEwnA5MDY9Bftr_iWCl1FNkeTOQ_lvL_AvvhXoFSnQjDq9y19xb_UD7--NtoBL6nMSwG6Q3EnN_lDi73PjYmhOH6RFaRnAWWlOBYFO8teC27pOtPQeKxoof74npQfPL2IUmhXznwx2JGRmafm0vsB28KO-a12Jlg44J40Tmc-WlqECN0CACZg6YeDJTW8_CdmPvLrUYrxvPfk_aODwppx9Oq9o6hJgvl8gaec3qA9znA&amp;scope=api+web+refresh_token+openid&amp;token_type=Bearer" enctype="application/x-www-form-urlencoded" id="redirectAsPost" method="POST" name="redirectAsPost" onsubmit="if (window.ffInAlert) { return false; }" ></form><script>document.redirectAsPost.submit();</script></body> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> <html> <head> <meta HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE"> </head> </html> ]
Unable to retreive the frontdoor URL. Message: */{"event":{"descriptor":"markup://aura:invalidSession","attributes":{"values":{"newToken":"invalid_csrf"}}},"exceptionMessage":"Expected 3 tokens in all","exceptionEvent":true}/*ERROR*/`

**Comment by gromgsxr** [comment]
i see the same works for aq while then just stops only way i can get it to go is by restarting ha

**Comment by Cosik** [comment]
@gromgsxr I will try to find today some time and investigate issue and try to fix it. I saw that it is in python so I should be able to do it.

**Comment by Cosik** [comment]
@gromgsxr  #43

**Comment by gvigroux** [comment]
Thanks to @Cosik, it seems to work better now
