### ISSUE TITLE
used wrong credentials

### ISSUE THREAD

**Issue by bennatzen** [gvigroux/hon#48]
hi there. I used the wrong credentials. When I try to add in HA a new device hon, a blank notification pop up appears. How can I reset the configuration? thanks and regards

**Comment by gvigroux** [comment]
The best is to delete the integration and reinstall again. 
I don't know why but no other integration propose to update the login/password once the integration is installed

**Comment by bennatzen** [comment]
Hi,

that was not possible because the Integration didnt appear in the
Integrations. I changed the hon credentials to the "wrong" pw and then the
Integration was shown in the ha Integrations.

Best regards

gvigroux ***@***.***> schrieb am So., 12. März 2023, 10:41:
