### ISSUE TITLE
[FEATURE REQUEST] Add Health modes to windDirectionVertical

### ISSUE THREAD

**Issue by pawelsky** [gvigroux/hon#55]
Hi, I've checked the implementation of https://github.com/gvigroux/hon/issues/31 and it seems to be working fine, thanks for that.

Haier AC has two additional windDirectionVertical modes called HEALTH airflow (one high and one low). Could you please add them as well?

Here are the corresponding numbers:
```
HEALTH_HIGH = 1
HEALTH_LOW = 3
```

**Comment by gvigroux** [comment]
Done :)
