### ISSUE TITLE
stuck on the integration configure step

### ISSUE THREAD

**Issue by vvnadolskyy** [gvigroux/hon#59]
Hi,
I'm trying to add this integration in my HA instance but all I get yet is "Unknown error occurred" error message.

![image](https://user-images.githubusercontent.com/12991410/227063221-b31d7419-5d21-423c-9f03-35d90c622e57.png)

Is it possible to debug it on my side somehow?

**Comment by gvigroux** [comment]
Did you look on the logs ? 
on path yourHAserver/config/logs

**Comment by gvigroux** [comment]
strange, working well on my side

**Comment by gvigroux** [comment]
No clue... sorry.
