### ISSUE TITLE
Add electricity usage as HA long-term statistics

### ISSUE THREAD

**Issue by ndom91** [gvigroux/hon#62]
So first of all, the latest update is great! I finally got all available fields from my washingmachine! 

However, when trying to add electricity usage to the built-in HA energy dashboard, the sensor is not available. 

They link to a statistics docs page for developers: 

- https://www.home-assistant.io/more-info/statistics/
- https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics 

Looks like you have to set the sensor `state_class` to one of `measurement`, `total` or `total_increasing`. I guess this one would be `total`, right? 

![Screenshot_2023-03-24-12-26-00-58_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/7415984/227509329-1e7d70f5-31f7-440f-890f-a27202146946.jpg)

Referring to this sensor: 

![Screenshot_2023-03-24-12-28-30-41_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/7415984/227509797-5ad844bb-469a-4610-83ab-b2bdf270fdea.jpg)

**Comment by gvigroux** [comment]
I just did it. Can you please test?

**Comment by ndom91** [comment]
Hmm so many of the sensors are no longer available anymore now. 

I got a second device added for my 1 washing machine with many fewer sensors:

![image](https://user-images.githubusercontent.com/7415984/227633040-b4ee4681-2284-428c-8d49-ab27f841dfff.png)


This is the previous one:

![image](https://user-images.githubusercontent.com/7415984/227633105-de50034b-7be3-41d9-88db-61322b48dc80.png)

All of these entities are now "no longer provided by the integration" :thinking: 

![Uploading image.png…]()

**Comment by gvigroux** [comment]
Can you please try to delete and reinstall the integration ?

**Comment by ndom91** [comment]
Deleted and readded the integration. Now I only have the 1 device with the 4 entities:

![image](https://user-images.githubusercontent.com/7415984/227651683-b4d57cc3-7971-481e-8206-028cff7d72d0.png)

**Comment by ndom91** [comment]
2 minutes later the washing machine sensors updated:

![image](https://user-images.githubusercontent.com/7415984/227651786-a9da27af-68ef-4b3c-a33b-327da8cc4b08.png)

**Comment by gvigroux** [comment]
Are more sensors coming after 1 min ?
I don't understand why they are not visible.

I've made some fix elsewhere, can you update and try ?
If the same, I need to analyse some logs to understand.
Please add this to the **configuration.yaml** and restart HA
```
logger:
  logs:
    custom_components.hon: info
```

After go to the log page '/config/logs' and click to access all logs.
Share any of the logs starting with:
`[custom_components.hon.hon] {"payload":`


Thanks!

**Comment by ndom91** [comment]
Ah found the issue, 

The `totalElectricityUsed` on `hon/sensor.py:129` is a `float`, not `int`. Therefore it failed setting up any sensors after that

Got all this after the change:

![image](https://user-images.githubusercontent.com/7415984/227718194-b608d376-dc83-4bc7-a762-238aa6e56164.png)

**Comment by ndom91** [comment]
In addition, I have htis error message in the logs:

> Entity sensor.washing_machine_current_water_used (<class 'custom_components.hon.sensor.HonBaseCurrentWaterUsed'>) is using state class 'measurement' which is impossible considering device class ('volume') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by ndom91** [comment]
As well as an issue with the `onOffStatus` key

![Uploading image.png…]()

**Comment by ndom91** [comment]
In addition, in `sensor.py:317` you're referring to `time` globally, and only defining it if the device is a `WASH_DRYER` type. Leading to errors for only `WASHING_MACHINE` type devices, for example

![image](https://user-images.githubusercontent.com/7415984/227719164-8ba7e952-286a-46e1-aa30-4a2964cc8fac.png)

**Comment by ndom91** [comment]
Ah works! Middle of a run cycle:

![image](https://user-images.githubusercontent.com/7415984/227719351-83ff7dba-7781-4e2c-834b-7764973c460e.png)

Although `startTime` is not right, thats the start time of the homeassistant instance (restarted). Looks like that might just be a side-effect of me redefining it in the middle of a washing cycle.

Anyway, sorry about the "stream of consciousness" bug reporting here :sweat_smile:. But after making all the changes I referenced in this thread, we seem to be up and running again :+1:

**Comment by ndom91** [comment]
And the actual issue raised in this GH issue is also fixed :joy:

![image](https://user-images.githubusercontent.com/7415984/227719454-67d54727-f9a0-4145-b8b6-c5c4fdbd54bb.png)

**Comment by ndom91** [comment]
Final question - is there any way to also control the devices through the API endpoints used for this integration?

Because logging in via the integration seems to kick me out of the android app, meaning I have to signin freshly again every time I want to start a cycle. Slightly annoying. Would be great if I could stay signed in only via hass and also initiate wash cycles via the integration.

**Comment by gvigroux** [comment]
Wow :) Can you create a pull request with all the changes? If not I will try and ask you test.

There is a service to start a washing program I think. Did you try?

**Comment by ndom91** [comment]
@gvigroux yeah no problem. Here we go :grin: 

https://github.com/gvigroux/hon/pull/64

I hadn't seen the service, I'll check it out! :pray:

**Comment by gvigroux** [comment]
I did the merge :) Thank you!
