### ISSUE TITLE
Add Hoover Tumble Dryer - HLE C10DCE-80

### ISSUE THREAD

**Issue by swampylee** [gvigroux/hon#63]
Hi, please can we look to get this model added to the integration. I installed it, rebooted etc and see a bunch of sensors but very few show any updates, More than happy to provide whatever details are needed. Here's what I see when I look at the hOn integration.

![image](https://user-images.githubusercontent.com/52431327/227720697-caa62628-f68b-4cda-b809-de24cf7aba3f.png)

**Comment by gvigroux** [comment]
Is there any error in the logs ?
Can you update first (just did a fix)

**Comment by gvigroux** [comment]
Should work now. Please reopen another issue if there are still an error
