### ISSUE TITLE
Wine cellar light status not reported correctly

### ISSUE THREAD

**Issue by Marcocanc** [gvigroux/hon#67]
The wine cellar binary sensor doesn't seem to be reporting the correct state (always shows off). Since I know you don't have a fridge to test this with, let me know if there's anything I can provide to help troubleshooting.

**Comment by gvigroux** [comment]
Ok, the service to turn on / off the light works ?

**Comment by gvigroux** [comment]
@Marcocanc, I just tested on my side and it works well for me. The status get an update every 30 seconds so it should not be longer than this (strange).
Can you see the real status via the mobile application ?

**Comment by Marcocanc** [comment]
You're right, I just deleted and reinstalled it. Seems to work fine now. Sorry for the false alarm, something was probably off about my previous install.
I'm assuming #54 didn't make it into the current version then?

**Comment by gvigroux** [comment]
Should work now :) Can you please confirm ?
