### ISSUE TITLE
Add Hoover Dishwasher HDPN 4S603PW/E

### ISSUE THREAD

**Issue by ojoaosemtil** [gvigroux/hon#69]
Hello!
Is it possible to add Hoover Dishwasher HDPN 4S603PW/E
I currently only see status and remote control.
Thank u!

**Comment by cylonbrain** [comment]
Try again, there was a patch from yesterday, that might have fixed that.

**Comment by gvigroux** [comment]
There is a service "turn_on_dishwasher" that should do the trick. Can you please test ?

**Comment by gvigroux** [comment]
There is now 1 service to launch any program.
If you prefer a different way to integrate, you can propose by opening a new issue :)
