### ISSUE TITLE
Latest code only finds remote control and status, no sensors (Hoover Tumble Dryer - HLE C10DCE-80)

### ISSUE THREAD

**Issue by swampylee** [gvigroux/hon#70]
As per the closed issue I raised, I have a Hoover Tumble Dryer - HLE C10DCE-80, before I was seeing sensors but most were not being updated. Since upgrading to the latest code now all I get are the Remote Control Status and the generic status as per the screenshot. I've removed the integration, restarted HA, reinstalled the integration and restarted HA twice bit still no other sensors are picked up.
![image](https://user-images.githubusercontent.com/52431327/228232762-685c8169-3bc6-463f-bab8-8b54b1c2c278.png)

**Comment by gvigroux** [comment]
Any error in the logs ?

**Comment by gvigroux** [comment]
In the last version, I removed the unnecessary sensors, I guess it's the reason. Which other sensor are available in the app you want to see in the integration?

**Comment by MrSleeps** [comment]
This should be fixed by the latest merge, might need a new release before HACS picks up the changes.

New sensors are shown in the pic.

![hon update](https://user-images.githubusercontent.com/9741713/232506499-9b1213ad-d0a5-4ee8-881e-27880d810bf2.png)
