### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by finalbillybong** [gvigroux/hon#76]
Hi when I try to add the intergration I get the following error.

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 74, in async_setup_entry
    await coordinator.device.load_commands()
  File "/config/custom_components/hon/device.py", line 182, in load_commands
    cmd = HonCommand(command, attr2, self._hon, self, multi=multi, program=program)
  File "/config/custom_components/hon/command.py", line 13, in __init__
    self._ancillary_parameters = self._create_parameters(attributes.get("ancillaryParameters", {}))
  File "/config/custom_components/hon/command.py", line 23, in _create_parameters
    result[parameter] = HonParameterRange(parameter, attributes)
  File "/config/custom_components/hon/parameter.py", line 53, in __init__
    self._min = int(attributes["minimumValue"])
ValueError: invalid literal for int() with base 10: '0,5'`

**Comment by gvigroux** [comment]
Thanks, i will fix it soon!

**Comment by gvigroux** [comment]
Can you please activate the debug (right click on the integration) and reboot HA ?
One big DEBUG log starting by "command" will be useful for me

**Comment by gvigroux** [comment]
Should work now  (I hope) :) I'm closing the ticket. please reopen if it's not working

**Comment by nathan-gs** [comment]
I have exactly the same error, with the latest commit (and 0.3.0). Any idea what's wrong @gvigroux

**Comment by gvigroux** [comment]
Are you sure you have the latest code ? I've made an update at this location.
Can you please dump the error one more time?

**Comment by gvigroux** [comment]
Should not happens anymore

**Comment by nathan-gs** [comment]
Verified it works now with latest 0.5.2-Beta2

**Comment by gvigroux** [comment]
thanks
