### ISSUE TITLE
[FEATURE REQUEST] Control Tumble Dryers

### ISSUE THREAD

**Issue by MrSleeps** [gvigroux/hon#82]
Would be helpful to be able to control Tumble Dryers (as you can Washing Machines).

**Comment by gvigroux** [comment]
coming in the next release :)

**Comment by MrSleeps** [comment]
Let me know if you need any testing, I'm more than happy to be a guinea pig!

**Comment by gvigroux** [comment]
Ok, I've made the first proposal :) please test.
If you prefer a different way to integrate, you can propose by opening a new issue :)
