### ISSUE TITLE
Washing Machine Program Control

### ISSUE THREAD

**Issue by schorschi1981** [gvigroux/hon#84]
Hey again thanks for your work. with the last update i receive all the individual program details. But there are only buttons for calling informations no one for initiate.
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/62060020/233195869-746c360e-544e-4abe-803c-70fd4632ee5a.png">

**Comment by gvigroux** [comment]
When clicking on the button, you will see some notificaitions with all details to launch the corresponding service

**Comment by schorschi1981** [comment]
thats quite possible if i would be able to know what i have to do with this informations. But anyway thank you.

**Comment by gvigroux** [comment]
Let me explain :) by clicking the button, you will receive some notifications that will guide you on how to launch a service and changing all parameters
