### ISSUE TITLE
Start and end time when launching washing program 

### ISSUE THREAD

**Issue by Heronimonimo** [gvigroux/hon#86]
Hi!

What a great integration, especially with the addition of being able to launch specific programs.

Would it be possible to add a start time when calling the default service that sets a program? That would be the last bit I need to replace using the app with my own HA setup.

**Comment by gvigroux** [comment]
You should be able to do that by using the "delayTime" value. Can you please try ? 
I think it's the delay before starting in Minutes

**Comment by Heronimonimo** [comment]
Just tested, this did not work.
`parameters: '{''delayTime'':''120''}'`
But might be to wrong syntax used.

**Comment by gvigroux** [comment]
can you please copy/paste the notification giving details about this specific program ? all parameters will be listed

**Comment by Heronimonimo** [comment]
Here you go:
```
Program [hqd_eco_40_60_degrees]
Parameters:
delayTime: [0 - 1410] - Default: 0
delayStatus: [0 - 1] - Default: 0
permanentPressStatus: [0 - 1] - Default: 0
```
Not sure what the delayStatus does. Do you know?

**Comment by gvigroux** [comment]
I don't know but sounds promising :) 
I would say:
{'delayTime':'10','delayStatus':'1'}

**Comment by Heronimonimo** [comment]
Tried this, it said minimal increment for delayTime is 30. Then ran it with 30 which still resulted in it starting directly.

**Comment by gvigroux** [comment]
strange, I do believe the delayTime is in Minute and I guess you also put the delayStatus to 1.
Any other parameter like "prTime" ?
