### ISSUE TITLE
Error setting up hOn app with climate devices

### ISSUE THREAD

**Issue by Keqi** [gvigroux/hon#87]
I get the following error when try to configure the hOn app in my HA:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hon/__init__.py", line 76, in async_setup_entry
    await coordinator.device.load_commands()
  File "/config/custom_components/hon/device.py", line 170, in load_commands
    self._appliance_model = commands.pop("applianceModel")
KeyError: 'applianceModel'
```

The models I am trying to add are `AS25XCAHRA` and `AS35XCAHRA` which are currently unsupported according to docs. Do you think we can add support to them or can I help doing that?

**Comment by gvigroux** [comment]
Sure, can you please activate the debug mode, and copy/paste the first logs ? (commands, context)

**Comment by Keqi** [comment]
@gvigroux I am sorry for the very silly questions but it will be my first time debugging a Python package. I have the environment installed but I need your instructions on how to run it locally and in the debug mode. Thanks!

**Comment by Keqi** [comment]
Ok, it seems that it must have been some configuration or API problem because the integration works perfectly now. Closing this issue. I also opened the PR to update the Readme: https://github.com/gvigroux/hon/pull/89
