### ISSUE TITLE
ambient temperature and humidity only updates during day

### ISSUE THREAD

**Issue by Therodoxx** [gvigroux/hon#88]
Hi, is it normal that the states for ambient temperature and humidity is not updated at night? I made a picture, there you can see very well that these values are updated only from 8-18 clock. 

![hon](https://user-images.githubusercontent.com/15246486/235270384-271ab348-caa9-4fed-a1e8-98600bd4cd27.png)

**Comment by gvigroux** [comment]
Hi, we get a new value every 30 seconds, so maybe the temperature stays at 18 all night?

**Comment by Heronimonimo** [comment]
I assume that precision is to low to see any changes most of the time.

**Comment by gvigroux** [comment]
yes, that's my theory

**Comment by gvigroux** [comment]
I'm closing this one. I guess it's working. (but it's a guess :))
