### ISSUE TITLE
 No control with Haier climate

### ISSUE THREAD

**Issue by ingcicala** [gvigroux/hon#90]
I used old version of HON integration ( before HACS including and with GitHub script installation) with my AS35S2SF1FA-MW3 climate and all worked .
Now I updated with HACS and It find my climate machine but it reports only FW version and it doesn't give me any control!!!
![Screenshot_20230425-075544](https://user-images.githubusercontent.com/62546009/235737674-a4f6d820-53c9-4e9a-b150-751c05d402a7.png)

**Comment by gvigroux** [comment]
Hi, the hOn integration in HACS is not mine :(, you can add my repo in HACS for an easy install.
