### ISSUE TITLE
How do I launch programmes?

### ISSUE THREAD

**Issue by Jaykurb** [gvigroux/hon#92]
I have noticed other people mention they can launch programmes from within HA using this integration but I can only see sensors. Is this dependant on models of appliances or am I missing something?

**Comment by gvigroux** [comment]
I just update the README, can you please look at it ?

**Comment by Jaykurb** [comment]
Many thanks

**Comment by gvigroux** [comment]
I don't know, sorry.
My only device is in remote mode (and I don't know how to turn this off)
