### ISSUE TITLE
Problema acceso

### ISSUE THREAD

**Issue by Hagory85** [gvigroux/hon#95]
Buenas me da error al meter usuario y contraseña (he cambiado 2 veces ya la contraseña y nada)…. Sabrías si hay algún error

**Comment by Therodoxx** [comment]
Check this https://github.com/gvigroux/hon/issues/94

**Comment by gvigroux** [comment]
Nothing interesting yet. I've started to look into it

**Comment by Hagory85** [comment]
> Check this #94

No he visto la solución... sabéis por que pasa esto?

**Comment by Hagory85** [comment]
Alguna noticia??

**Comment by gvigroux** [comment]
should be fixed now :)

**Comment by gvigroux** [comment]
Can someone test?

**Comment by gvigroux** [comment]
works on my side. Same error ?

**Comment by Jaykurb** [comment]
Sorry this might be my bad. Think my account details are actually wrong from when I changed recently. Will let you know if the update works when I'm home (if no one else has prior to that).

**Comment by TrustedFloppa** [comment]
I tested it, its not working :(
![image](https://github.com/gvigroux/hon/assets/85476585/91972842-28b5-4cda-8e5f-72977e32913b)

**Comment by gvigroux** [comment]
Do you have an error in the logs ? It works well on my side.

**Comment by Hagory85** [comment]
Sigue todo igual….

**Comment by Hagory85** [comment]
![Uploading 7D21787E-DD2E-4BAD-ADDB-448A05619BAF.jpeg…]()

**Comment by gvigroux** [comment]
Did you restart HA after the update?

**Comment by heatzor** [comment]
I've deleted the integration.
Removed the custom repository, then added it again.
Installed the integration and restarted, but it says wrong password.
I've even tried changing the password and trying with a new one, but I still can't login.

This error originated from a custom integration.

Logger: custom_components.hon.hon
Source: custom_components/hon/hon.py:185
Integration: hOn (documentation, issues)
First occurred: 6:08:16 PM (1 occurrences)
Last logged: 6:08:16 PM

hOn Invalid Data [<coroutine object ClientResponse.text at 0x7f8a0121f0>] after sending command [{'mobileId': '2de50955d6b20d9a', 'os': 'android', 'osVersion': 31, 'appVersion': '1.53.7', 'deviceModel': 'goldfish_x86'}] with headers []{'Content-Type': 'application/json', 'id-token': 'XXXXXXXXXXXXXXXXXXXXX'}]

**Comment by gvigroux** [comment]
I changed this log in the latest release. It means that you don't have the latest version.
(I'm not using "goldfish_x86" anymore but "exynos9820" instead)

**Comment by gvigroux** [comment]
I think I know why !!!! I didn't create a new release base on my code.
It's done now

**Comment by gvigroux** [comment]
It was working before ?

**Comment by gvigroux** [comment]
@TrustedFloppa can you please open another case for your problem ?
Do you have any specific log?
