### ISSUE TITLE
[feature request] Control over airflow direction

### ISSUE THREAD

**Issue by lechoooo** [gvigroux/hon#98]
Hi,

Would it be possible to add a control over fixed airflow direction for the Haier AC's ? 
i.e. AC is cooling and the airflow is being directed to far left, and to the top.
Currently there is a possibility to steer the swing motion only.
Thank you for considering this.

**Comment by gvigroux** [comment]
This is not part of default HA climate device so I've added 2 services already:
- hOn: Set wind direction horizontal
- hOn: Set wind direction vertical

Can you please test?

**Comment by lechoooo** [comment]
Works perfectly, thanks for that !

**Comment by gvigroux** [comment]
cool :)
